-- KAIRONIX SSOMA 360 - CONFIGURACIÓN INICIAL DE SUPABASE
-- Ejecutar todo este archivo en Supabase > SQL Editor > New query.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text not null,
  email text not null unique,
  rol text not null default 'Consulta' check (rol in ('Administrador','Inspector','Consulta')),
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.unidades (
  id bigint generated by default as identity primary key,
  placa text not null unique,
  tipo text not null,
  marca text,
  modelo text,
  anio integer,
  empresa text default 'RANSA',
  agencia text default 'Huachipa',
  estado text not null default 'Activo',
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.inspecciones (
  id bigint generated by default as identity primary key,
  unidad_id bigint references public.unidades(id) on delete cascade,
  placa text not null,
  fecha date not null default current_date,
  inspector_id uuid references auth.users(id),
  inspector_nombre text,
  kilometraje numeric default 0,
  conos boolean not null default false,
  tacos boolean not null default false,
  botiquin boolean not null default false,
  extintor boolean not null default false,
  luces boolean not null default false,
  neumaticos boolean not null default false,
  cinturones boolean not null default false,
  documentos boolean not null default false,
  resultado text not null check (resultado in ('Conforme','Observada')),
  observacion text,
  evidencia_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.hallazgos (
  id bigint generated by default as identity primary key,
  inspeccion_id bigint references public.inspecciones(id) on delete cascade,
  placa text not null,
  fecha date not null default current_date,
  categoria text not null,
  descripcion text not null,
  criticidad text not null check (criticidad in ('Baja','Media','Alta','Crítica')),
  responsable text,
  fecha_compromiso date,
  estado text not null default 'Abierto' check (estado in ('Abierto','En proceso','Subsanado')),
  evidencia_url text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create index if not exists idx_inspecciones_fecha on public.inspecciones(fecha);
create index if not exists idx_inspecciones_placa on public.inspecciones(placa);
create index if not exists idx_hallazgos_estado on public.hallazgos(estado);

alter table public.profiles enable row level security;
alter table public.unidades enable row level security;
alter table public.inspecciones enable row level security;
alter table public.hallazgos enable row level security;

create or replace function public.current_role()
returns text language sql stable security definer set search_path = public
as $$ select rol from public.profiles where id = auth.uid() and activo = true $$;

drop policy if exists profiles_own_read on public.profiles;
create policy profiles_own_read on public.profiles for select to authenticated
using (id = auth.uid() or public.current_role() = 'Administrador');

drop policy if exists profiles_admin_write on public.profiles;
create policy profiles_admin_write on public.profiles for all to authenticated
using (public.current_role() = 'Administrador') with check (public.current_role() = 'Administrador');

drop policy if exists unidades_read on public.unidades;
create policy unidades_read on public.unidades for select to authenticated using (true);
drop policy if exists unidades_write on public.unidades;
create policy unidades_write on public.unidades for all to authenticated
using (public.current_role() in ('Administrador','Inspector'))
with check (public.current_role() in ('Administrador','Inspector'));

drop policy if exists inspecciones_read on public.inspecciones;
create policy inspecciones_read on public.inspecciones for select to authenticated using (true);
drop policy if exists inspecciones_write on public.inspecciones;
create policy inspecciones_write on public.inspecciones for all to authenticated
using (public.current_role() in ('Administrador','Inspector'))
with check (public.current_role() in ('Administrador','Inspector'));

drop policy if exists hallazgos_read on public.hallazgos;
create policy hallazgos_read on public.hallazgos for select to authenticated using (true);
drop policy if exists hallazgos_write on public.hallazgos;
create policy hallazgos_write on public.hallazgos for all to authenticated
using (public.current_role() in ('Administrador','Inspector'))
with check (public.current_role() in ('Administrador','Inspector'));

insert into storage.buckets (id, name, public)
values ('evidencias','evidencias',true)
on conflict (id) do update set public = true;

drop policy if exists evidencias_read on storage.objects;
create policy evidencias_read on storage.objects for select using (bucket_id='evidencias');
drop policy if exists evidencias_insert on storage.objects;
create policy evidencias_insert on storage.objects for insert to authenticated
with check (bucket_id='evidencias');

-- IMPORTANTE: después de crear tu primera cuenta en Authentication > Users,
-- reemplaza los datos siguientes y ejecuta SOLO este INSERT:
-- insert into public.profiles (id,nombre,email,rol,activo)
-- values ('UUID_DE_AUTH_USERS','Geerson Llaja Escalante','TU_CORREO','Administrador',true);

